Event Cultist Ship
voidcrew/Voidcrew-LRP pull request #162
Opened 2022-02-10 07:14 UTC by BlackCat-055

## About The Pull Request
I made a Ship that's cultist in theme, essentially was originally an Express Cargo Freighter that got hijacked by Nar'sian cultists as a base of operations. Figured something like this could be done for events!

![scrnshot](https://user-images.githubusercontent.com/87887958/153355954-4e602e60-2a7c-4a30-9b6a-9fd3f2b12736.png)

## Why It's Good For The Game

Because funny Cultship that can be used for events to spice things up. It gives cultists for a possible cultist event a fitting headstart-ish on their Cult stuff.

## Changelog
:cl:
add: A Cultist Ship!
config: Did the cultist ship config
/:cl:

2022-02-10 12:42 UTC, SuperNovaa41 commented
Don't merge until i add da thing to make people cultists

2022-02-10 22:33 UTC, Jackriip commented
test merging

2022-02-10 22:33 UTC, Jackriip commented
nevermmind you need to add that antag status json thing

2022-02-10 23:03 UTC, BlackCat-055 commented
All done now! At least from what I can see

2022-02-10 23:13 UTC, BlackCat-055 commented
I maay have to fix some things.

2022-02-11 02:42 UTC, BlackCat-055 commented
Yeah I dont know how to test ships but I think everything works

2022-02-12 20:49 UTC, dwasint commented
it works gonna hold off on tm'ing or merging until parts works

2022-02-13 17:59 UTC, Jackriip requested changes

2022-02-13 17:59 UTC, Jackriip commented on _maps/configs/KOS_express_cultist.JSON
> +			"slots": 3
bad json

2022-02-13 18:56 UTC, SuperNovaa41 commented
It doesn't work, the json file is missing a bracket, and it has trailing commas. Also the map file doesn't have a docking port
![image](https://user-images.githubusercontent.com/16159590/153770268-89cc9bdf-1193-4a9e-8064-3f62fcce7301.png)

2022-02-19 19:54 UTC, closed without merging