Adds nooses and the ability to hang yourself/others
voidcrew/Voidcrew-LRP pull request #176
Opened 2022-02-11 22:43 UTC by SweptWasTaken

## About The Pull Request

Ported from https://github.com/BeeStation/BeeStation-Hornet, but the original PR was ported to Beestation from https://github.com/HippieStation/HippieStation with minor changes by me to make it compatible for Voidcrew.

When standing on a chair, you'll be able to tie a noose to the ceiling. You can then click-drag yourself onto it to hang yourself or drag someone else on it to hang them. Someone can push you over while getting into a noose, or cut the noose while you're swaying in it.

I tested it a bunch and everything looks functional.

## Why It's Good For The Game

Allows you to commit suicide in a poignant way, with enough flair and time in-between getting in the noose and dying for someone to be your savior and cut you down.

## Changelog
:cl: Swept
add: Ported nooses and hanging from Beestation-Hornet
/:cl:

2022-02-11 22:44 UTC, ShibaInuLord commented
based and hippiepilled

2022-02-11 22:45 UTC, DAKKA-WAAAGH commented
Very based

2022-02-11 22:56 UTC, dwasint requested changes
This can be put in the voidcrew folder to the same path just fine. Probably best if all new stuff is put there for the rebase

2022-02-11 23:13 UTC, SuperNovaa41 requested changes
Modularize everything, including the sounds and images. and FIX ALL YA DAMN VAR NAMES

2022-02-11 23:13 UTC, SuperNovaa41 commented on code/game/objects/noose.dm
> +/obj/item/stack/cable_coil/building_checks(datum/stack_recipe/R, multiplier)
```suggestion
/obj/item/stack/cable_coil/building_checks(datum/stack_recipe/R, multiplier)
```
better var names

2022-02-11 23:13 UTC, SuperNovaa41 commented on code/game/objects/noose.dm
> +	var/mutable_appearance/overlay
doc this

2022-02-11 23:13 UTC, SuperNovaa41 commented on code/game/objects/noose.dm
> +/obj/structure/chair/noose/attackby(obj/item/W, mob/user, params)
just use wirecutter act

2022-02-12 00:01 UTC, theta006 commented
YOU SHOULD KILL YOURSELF NOW

2022-02-12 19:38 UTC, JohnFulpWillard commented on code/modules/power/cable.dm
> +GLOBAL_LIST_INIT(cable_coil_recipes, list (new/datum/stack_recipe("cable restraints", /obj/item/restraints/handcuffs/cable, 15), new/datum/stack_recipe("noose", /obj/structure/chair/noose, 30, time =
☹️

2022-02-12 20:03 UTC, SuperNovaa41 commented on code/modules/power/cable.dm
> +GLOBAL_LIST_INIT(cable_coil_recipes, list (new/datum/stack_recipe("cable restraints", /obj/item/restraints/handcuffs/cable, 15), new/datum/stack_recipe("noose", /obj/structure/chair/noose, 30, time =
i agree with john

2022-02-12 20:14 UTC, SweptWasTaken commented
> Modularize everything, including the sounds and images. and FIX ALL YA DAMN VAR NAMES

Done.

I fixed some of the var names but I don't see why some of them can be just left.

2022-02-12 20:46 UTC, SuperNovaa41 requested changes
Still a lot of bad var names here. There shouldn't be any single letter variable names.

2022-02-12 20:46 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +	//So that the noose sprite can overlay the person beind hanged.
```suggestion
	///So that the noose sprite can overlay the person beind hanged.
```
Triple /// are used for documenting comments

2022-02-12 20:46 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +		for(var/m in buckled_mobs)
Theres still bad var names here >:(

2022-02-12 20:46 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +	var/obj/item/stack/cable_coil/C = new(get_turf(src))
here too

2022-02-12 20:46 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +/obj/structure/chair/noose/post_buckle_mob(mob/living/M)
here

2022-02-13 00:52 UTC, SuperNovaa41 requested changes
Last things i promise

2022-02-13 00:52 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +	if(has_buckled_mobs())
everything in this proc only passes if `has_buckled_mobs()` is true, just make this an early return

2022-02-13 00:52 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/noose.dm
> +		if(buckled_mob.has_gravity())
same here, but early continue

2022-02-13 07:07 UTC, SuperNovaa41 commented
This was pretty funny, but I don't really want this. It'll quickly become unfunny. gonna leave this open for a bit longer

2022-02-15 20:31 UTC, SweptWasTaken commented
I'm closing this until after the rebase is finished, then i'll immediately open it again and get it merged.

2022-08-13 00:34 UTC, Sbmhawk commented
what have you done

2022-09-07 15:50 UTC, SuperNovaa41 commented
Fix linter issues

2022-11-13 21:33 UTC, closed without merging