Beach Planet
voidcrew/Voidcrew-LRP pull request #223
Opened 2022-02-16 15:07 UTC by Jackriip

atvs jukeboxes lots of booze a gun arachnids slimes multi-biome custom tendrils ships yadadadada

2022-02-17 00:38 UTC, ShibaInuLord commented
wouldnt it be cooler if the serpent tails were called kraken tentacles instead or something

2022-02-18 05:57 UTC, ShibaInuLord commented
another idea- maybe rename the planet to ocean planet to better fit the naming convention?

2022-02-18 16:59 UTC, SuperNovaa41 commented
Your maps should be saved in TGM mode. (Open in SDMM -> Prefernces -> saving mode: TGM -> Save)

2022-02-18 17:01 UTC, SuperNovaa41 requested changes
Ok so theres a couple more of these, fix all the uhh single letter var names pls :)

2022-02-18 17:01 UTC, SuperNovaa41 commented on voidcrew/code/datums/mapgen/BeachGenerator.dm
> +	for(var/t in turfs) //Go through all the turfs and generate them
```suggestion
	for(var/turf in turfs) //Go through all the turfs and generate them
```

2022-02-18 17:01 UTC, SuperNovaa41 commented on voidcrew/code/datums/mapgen/BeachGenerator.dm
> +		var/area/A = gen_turf.loc //meet my friends, Ctrl+C and Ctrl+V!
```suggestion
		var/area/area = gen_turf.loc //meet my friends, Ctrl+C and Ctrl+V!
```

2022-02-18 22:22 UTC, Jackriip commented
Continuing to add to this, don't merge it

2022-02-18 22:51 UTC, SuperNovaa41 commented
Even better we should wait until my planet refactor is merged before we merge this :)

2022-02-22 17:38 UTC, SuperNovaa41 requested changes
A lot of this looks really good! just a few things need changing

2022-02-22 17:38 UTC, SuperNovaa41 commented on code/__DEFINES/sound.dm
> +#define BEACH list('sound/ambience/shore.ogg', 'sound/ambience/seag1.ogg','sound/ambience/seag2.ogg','sound/ambience/seag2.ogg','sound/ambience/ambiodd.ogg','sound/ambience/ambinice.ogg')
move this into `code/__DEFINES/__VOID_DEFINES/sound.dm`

2022-02-22 17:38 UTC, SuperNovaa41 commented on shiptest.dme
> +#include "voidcrew\code\_globalvars\lists\flavor_misc.dm"
these are all placed in the wrong place.. redo this and put them in the proper alphabetical spot. Dreammaker likes to force rearrange these and i'd rather have them all done here so someone else's PR doesn't throw this in

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/datums/ruins/beach.dm
> +/datum/map_template/ruin/beach/fishinghut
make a generic `/datum/map_template/ruin/beach/` and put the prefix there, so you don't have to include it with every single ruin

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/structures/beach/serpent_tail.dm
> +	var/obj/effect/light_emitter/tail/tail_emitted_light
make sure to put a comment with `///` on the line before these and document what they do

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/game/objects/structures/beach/serpent_tail.dm
> +	for(var/F in RANGE_TURFS(1, src))
no single letter variables ALLOWED

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/modules/mob/living/simple_animal/friendly/beachcarp.dm
> +/mob/living/simple_animal/voidcarp/Life()
`/mob/living/simple_animal/voidcarp` doesn't exist. one of these two paths is wrong

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/modules/vehicles/atv.dm
> +	name = "no key atv"
```suggestion
	name = "atv"
```
It's in the description

2022-02-22 17:38 UTC, SuperNovaa41 commented on voidcrew/code/modules/vending/boozeomat.dm
> +	desc = "A Booze-O-Mat that appears to have its source of energy, as well as a completely free selection of items"
```suggestion
	desc = "A conventiently placed Booze-O-Mat, seems to have free drinks!"
```
bike shedding but like im sure most people don't care about if it uses power, they will just see funny drink machine

2022-02-22 18:15 UTC, closed without merging