Removes Squid Inking
voidcrew/Voidcrew-LRP pull request #320
Opened 2022-03-05 23:55 UTC by alexeric123

## About The Pull Request

Removes the ink ability from squids pending whenever someone decides to rework it.

## Why It's Good For The Game

I have never seen a squid not ink their entire ship, just to laugh at those that slip on them.

Giving a round start race this ability is stupid.
Has been requested multiple times.

2022-03-06 00:07 UTC, ShibaInuLord commented
Ided

2022-03-06 00:28 UTC, Dethstorm commented
Clearly a required nerf, this will surely contribute to our RP standards.

2022-03-06 00:31 UTC, LtFuzz commented
Yes, we must retain RP standards.

2022-03-06 01:56 UTC, alexeric123 commented
Reopen if you want novaa

2022-03-06 01:57 UTC, alexeric123 commented
Wrong button lmao

2022-03-06 03:31 UTC, SuperNovaa41 requested changes
Why are you just commenting everything out? Also, if you remove this they're just normal humans. so WE should just remove them entirely :))))

2022-03-06 03:50 UTC, alexeric123 commented
I commented it out so it could be readded in a different way, if it was ever decided on.
Should I delete all that instead?
Or should I just change squiddies to not be a roundstart race?

2022-03-06 06:39 UTC, ShibaInuLord commented
> I commented it out so it could be readded in a different way, if it was ever decided on. Should I delete all that instead? Or should I just change squiddies to not be a roundstart race?

squids not being roundstart is a config option

2022-03-06 06:49 UTC, Sbmhawk commented
yes i know

2022-03-07 12:37 UTC, SuperNovaa41 commented
Fine by me ill just remove them later (i hate squids)

2022-03-07 12:37 UTC, merged