Ports two PRs from TG & Shiptest. [0% Tested, probably broke]
voidcrew/Voidcrew-LRP pull request #427
Opened 2022-08-18 09:52 UTC by githubuser4141

## About The Pull Request

Semi-Port of [TG's hair rework](https://github.com/tgstation/tgstation/pull/67184). Removes the problematic hair styles mentioned in the comments.

Ports [](https://github.com/shiptest-ss13/Shiptest/pull/1015)

## Why It's Good For The Game

Shutters/Blastdoors are now buildable! Yay! Adds more options to fortify or decorate your ship, which is almost always a plus.

A lot of the hair styles used currently are horrendously outdated; this should help freshen the look of our spesspeople! Hopefully.

!This PR hasn't been tested and inf act runtimed to oblivion when I tried to launch it, this may or may not be related. Haven't had time to thoroughly test it yet so I'll make this a draft.

## Changelog
:cl:
tweak: Blastdoors/shutters now craftable! Hairstyles updated to pricier $250-worth sprites!

2022-08-18 19:51 UTC, PeriodicChaos commented
I would not add the hair one as the tg people said it looks bad instead i would port their custom charter system without that hair or added with  the old hair

2022-08-22 01:06 UTC, githubuser4141 commented
pls review and/or merge :)

2022-08-22 19:50 UTC, PeriodicChaos commented
I think you should not change the hair but add to it if you could as people don't like their hair they used randomly changing

2022-08-23 07:58 UTC, githubuser4141 commented
> I think you should not change the hair but add to it if you could as people don't like their hair they used randomly changing

The sprites changed are generally superior to the ones replaced. Making them unique styles would add a ton of clutter and there's no real need for it. It's a sprite upgrade and the troublesome sprites brought up in the TG port were removed. Also, it's a LRP server where most people walk around in space suits/mechs/helmets, I doubt many people would mind.

2022-08-25 02:05 UTC, PeriodicChaos commented
> > I think you should not change the hair but add to it if you could as people don't like their hair they used randomly changing
> 
> The sprites changed are generally superior to the ones replaced. Making them unique styles would add a ton of clutter and there's no real need for it. It's a sprite upgrade and the troublesome sprites brought up in the TG port were removed. Also, it's a LRP server where most people walk around in space suits/mechs/helmets, I doubt many people would mind.

I'm sorry to say but LRP does not mean I don't care about how stuff looks also you call it a sprite upgrade I call it a replacement you should just change it so you're adding not replacing with stuff people would not want unless they could willingly pick it and yes, some people did mind it does not matter how much you remove it does not make it nicer.

2022-08-27 08:34 UTC, githubuser4141 commented
yeah, that's not at all practical for a sprite upgrade and literally not how any sprite replacement has ever worked. Removes the hair sprite replacement for this PR now so people can fuck with blast doors

2022-09-07 15:49 UTC, SuperNovaa41 requested changes

2022-09-07 15:49 UTC, SuperNovaa41 commented on code/game/machinery/doors/poddoor.dm
> +	if((resistance_flags & INDESTRUCTIBLE) && W.tool_behaviour == TOOL_SCREWDRIVER) // This makes it so ERT members cannot cheese by opening their blast doors.
we have `screwdriver_act` `multitool_act` `crowbar_act`, etc. Use these.

2022-09-07 15:49 UTC, SuperNovaa41 commented on code/game/objects/structures/poddoor_assembly.dm
> +/obj/structure/poddoor_assembly/attackby(obj/item/item_used, mob/user, params)
same here

2022-11-13 21:33 UTC, closed without merging