Head of Staff hardsuit crates
voidcrew/Voidcrew-LRP pull request #442
Opened 2022-08-23 08:20 UTC by GuiltyNeko

## About The Pull Request
Cargo crates for the CE, RD, and HoS hardsuits. CMO was ignored because the only difference over the medical hardsuit in this code is the flash protection in the helmet, and eh.

CE and RD hardsuits cost 100K, HoS hardsuit costs 120K, prices negotiable. 

## Why It's Good For The Game
Head of staff hardsuits are solid equipment generally intended to be fielded against relevant threats in-game, which you generally are unable to do on voidcrew due to lack of the hardsuits. This gives you those options back, if you're willing to pay for it. I don't think the HoS hardsuit will change combat balance due to combat balance being around the even-higher-tier hardsuits such as the syndie and ERT hardsuits.

## Changelog
:cl:
add: You can now buy the Chief Engineer's Hardsuit, the Research Director's Hardsuit, and the Head of Security's hardsuit from cargo.
/:cl:

2022-08-24 03:47 UTC, githubuser4141 commented
I think 100,000 credits is a bit much for a single hardsuit that's generally worse then the other (ERT, Heavy Mining, Syndie) hardsuits. 5k to 10k would probably be in line with the other specialty items.

2022-08-24 07:57 UTC, GuiltyNeko commented
I'm mainly trying to avoid a situation in which you're able to afford to give your entire crew one of these, because they're meant to be unique, not something you can just hand out willy nilly and get a replacement for at no major cost.

2022-09-06 02:35 UTC, SuperNovaa41 requested changes

2022-09-06 02:35 UTC, SuperNovaa41 commented on code/modules/cargo/packs.dm
> +	desc = "A spare Research Director's Hardsuit in case the first one wasn't explosion-proof enough"
```suggestion
	desc = "A spare Research Director's Hardsuit in case the first one wasn't explosion-proof enough."
```

2022-09-09 16:06 UTC, SuperNovaa41 approved these changes

2022-09-09 16:06 UTC, merged