Crude CircuitBoards
voidcrew/Voidcrew-LRP pull request #453
Opened 2022-08-27 01:56 UTC by PeriodicChaos

## About The Pull Request

**_I will make sprites later_**
I have made **Crude Circuit Boards** so people could make ships from nothing more than a pickaxe here is a list of what I added.

- Added **Crude Engine**
- Added **Crude Pacman**
- Added **Crude Helm Board**
- Added **Crude Board Component**
- Added **Crude Board**
- Added **Craftable Coil**
- Added **Craftable Blueprints**

**_I may add an autolathe board sooner or later._**
## Why It's Good For The Game

Makes Blackpill Possible to get RnD from and people can land their ship and run off on their own and make their own ship from nothing i think that would be a fun idea for people to do.

## Changelog
:cl:
add: Added Crude Engine
add: Added Crude Pacman
add: Added Crude Helm Board
add: Added Crude Board Component
add: Added Crude Board
add: Added Craftable Coil
add: Added Craftable Blueprints
/:cl:

2022-09-02 04:55 UTC, SuperNovaa41 commented on code/modules/power/cell.dm
> -	maxcharge = 300
why the subtle potato cell buff

2022-09-02 20:15 UTC, PeriodicChaos commented on code/modules/power/cell.dm
> -	maxcharge = 300
its debuffed it should be

2022-09-02 20:42 UTC, GuiltyNeko commented on code/game/objects/items/circuitboards/machine_circuitboards.dm
> +	req_components = list(/obj/item/stack/ore/iron = 2,
You'll need a capacitory in here or else you'll get zero power output in port_gen.dm when it grabs the temp rating.

2022-09-07 02:19 UTC, GuiltyNeko requested changes
To be clearer, and to request changes officially, the pacman needs a capacitor or it won't work, and will runtime. This needs to be fixed before this can be merged.

2022-09-07 18:09 UTC, Addust commented
grug boardman

2022-09-08 06:11 UTC, GuiltyNeko requested changes

2022-09-08 06:11 UTC, GuiltyNeko commented on code/datums/components/crafting/recipes.dm
> +/datum/crafting_recipe/helm
This has the same datum name as the recipe below it, so it gets overwritten by that one, making this recipe uncraftable.

2022-09-08 22:34 UTC, GuiltyNeko commented
Test Merging

2022-09-11 13:58 UTC, GuiltyNeko requested changes
And the autolathe needs a matter bin to hold materials.

2022-10-03 01:55 UTC, closed without merging