Adds Recharger and fixes tanks (NanoPill)
voidcrew/Voidcrew-LRP pull request #458
Opened 2022-08-31 01:58 UTC by PeriodicChaos

## About The Pull Request

Add recharger and fixes tanks with no air

## Why It's Good For The Game

People want a recharger on it and i need to fix the tanks

## Changelog
:cl:
add: Added Recharger and fixes tanks to NanoPill
/:cl:
![image](https://user-images.githubusercontent.com/44913068/187575858-0271025d-dec1-4b27-89b9-23f564296730.png)

2022-09-02 11:52 UTC, dwasint commented
i generally dislike items just being on the floor but aside from that it looks good

2022-09-02 11:52 UTC, dwasint approved these changes

2022-09-07 02:01 UTC, GuiltyNeko commented
Test merging

2022-09-15 19:22 UTC, GuiltyNeko requested changes
While you're there I'd like you to change the dir on that closet so it's facing inwards and not outwards. I know what tile it's on, but visually, it's facing towards the outside of the ship. After that I'll merge this.

2022-10-03 14:26 UTC, GuiltyNeko approved these changes

2022-10-03 14:27 UTC, merged