Voidcrewing shiptest name replacement
voidcrew/Voidcrew-LRP pull request #469
Opened 2022-09-03 19:43 UTC by PeriodicChaos

## About The Pull Request

Just renaming stuff (a lot of stuff) I have read it over it should all be fine you can read it over as well

## Why It's Good For The Game

So we don't need to rename stuff later and it makes it shows we can be our own thing

## Changelog
:cl:
add: Added Lots of renames
/:cl:
![image](https://user-images.githubusercontent.com/44913068/188285634-22f64315-aa06-4367-9854-8b4b1996a3f4.png)

2022-09-03 19:45 UTC, JohnFulpWillard commented
me when me wheni when i find replace functi on

2022-09-03 19:50 UTC, PeriodicChaos commented
> me when me wheni when i find replace functi on

Indeed

2022-09-03 20:46 UTC, GuiltyNeko commented on code/datums/ruins/icemoon.dm
> -/datum/map_template/ruin/icemoon/slimerancher //Shiptest edit
I feel like it's incredibly unnecessary to wipe shiptest out of comments, that removes a significant amount of context from "why was this decision made?"

2022-09-03 20:47 UTC, GuiltyNeko commented on code/datums/ruins/space.dm
> +/* voidcrew: derelict is too big. we're commenting it out for now
In this instance, renaming shiptest to voidcrew implies we made this decision, but we didn't. We shouldn't blame ourselves for actions that are not ours.

2022-09-03 20:48 UTC, GuiltyNeko commented on config/config.txt
> +# SERVERNAME voidcrew
If you're going to take this seriously, capitalize voidcrew where shiptest was capitalized.

2022-09-03 20:49 UTC, GuiltyNeko commented on html/changelogs/.all_changelog.yml
> +  - code_imp: The dream maker enviroment has been renamed to voidcrew.
Absolutely do not rename shiptest to voidcrew in the changelogs, that's as rude as you get.

2022-09-06 17:03 UTC, SuperNovaa41 requested changes
Why did you delete `.vscode/settings.json` please do not do this.

Don't touch the changelog, don't change the comments that are `shiptest edit` or whatever else they may be. Those weren't us I'd rather have those documented

2022-09-06 23:47 UTC, closed without merging

2022-09-06 23:47 UTC, PeriodicChaos commented
eh it was a joke pull anyways