Added whole complete project
voidcrew/Voidcrew-LRP pull request #471
Opened 2022-09-07 20:50 UTC by BBBBAface

## About The Pull Request

Shiptest didn't want it so here is a ship I spent about 20 hours working on. There weren't any ships like it on Shiptest; I'm not sure if there are any plasma tankers on this codebase or not, but here's the fully functioning ship.

This PR adds a new Nanotrasen ship to the game, A plasma transport vessel with limited facilities but enough plasma to last a large settlement indefinitely.

![image](https://user-images.githubusercontent.com/19318747/188257104-8a016422-6d88-4a5b-9fbb-5d04223e8966.png)

Specs:
Limited to 2 per round
440Ton weight with 6 ion engines
Supports a crew of up to 7, but works best with 3 - 5 Power-management system 
Around 2,500,000 MOL of plasma gas
5,000cr starting cash
Stocked medbay
Extremely limited weaponry
Basic mining gear
Working Exterior / Engine / Bay shutters and holofans
"Robust" atmos setup
Outpost comms console

Pros: 
• You will never run out of plasma gas
• Defribulator and surgical tools
• A cell for troublesome patients
• Engineering protolathe
• Large bay doors and engineering area
• Easily customizable
• Only ship of its kind
• Slot machine!
• Shoilet!

Cons:
• NO R&D capabilities
• NO Projectile weapons and limited security gear in general (that's a cap gun on the bridge)
• NO way of actually utilizing the plasma it has stored
• Only 3 hardsuits
• No launchpad or outpost trading console
• Slightly cramped design
• No insulated gloves; you're going to have to drink Rubbernecks

![image](https://user-images.githubusercontent.com/19318747/188257032-bf00476b-f7c3-4917-a035-fc48749cf409.png)

![image](https://user-images.githubusercontent.com/19318747/188257052-83c36cf8-7043-40e0-b43d-62193c71a424.png)

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

Currently, no ships are designed to trade gas, leaving the niche unfilled. This is the solution.

This ship would be a decent trading vessel, and because of the defibrillator, it could also make a good emergency response vessel, able to refuel ships and revive the crew. Lack of plasma engines or TEG means the plasma gas is useless on round start. Trading with other players is required due to the lack of research capabilities.

## Changelog

:cl:
Add: the completed ship 
Fixed: errors
Add: 1 fire extinguisher
Replaced: APC console with Computer Frame
Replaced: Roulette with Orion Trail
Rotated: Orion Trail
Add: Outpost Comms Console
Fix: docking port and size of map
Removed: Most of the sec gear (there are now extremely limited weapons on the ship)
Added: Recharger (there is nothing to recharge, this is for decoration)
Replaced: Floor in Engineering
Added: 1 Tile of length to the ship
Added: New posters and trim
/:cl:

2022-09-07 20:55 UTC, MoonFalcon commented
Looks like it's failing linting. Really like the ship by the way

2022-09-07 21:46 UTC, PeriodicChaos commented
Nice ship i hope to see it ingame no idea why shiptest would want to give this up.

2022-09-07 21:47 UTC, PeriodicChaos commented
heres the error something about an id 
![image](https://user-images.githubusercontent.com/44913068/188989136-015ddcf4-3998-46e4-a56e-4a4a40088dd5.png)

2022-09-07 21:48 UTC, Jackriip commented
Looks great! I'd be happy to test merge it if you get the linting fixed

2022-09-07 22:14 UTC, BBBBAface commented
> Nice ship i hope to see it ingame no idea why shiptest would want to give this up.

they said to wait for a rework to "the gas economy" and redo the pr when that's done, so basically just wait indefinitely.

2022-09-08 06:26 UTC, GuiltyNeko requested changes
Window spawners spawn grilles under them, you should remove the grilles on the same tiles as your window spawners. In addition, you should put the ID back on the door, the linters just didn't like the ID var on the docking port. I'd also like you to replace the bridge holopad with a holopad/emergency/command, as most/all of our ships have one and that one in particular can help with access issues faced by a crew. And if I remember correctly, cyclelink helpers only work on doors in cardinal directions from each other. If you want the airlock to cycle in that way you'll need cyclelink_helper_target.

2022-09-08 06:26 UTC, GuiltyNeko commented on _maps/Configs/nanotrasen_tanker.json
> +	"prefix": "NTSV",
This will need to be "NEU", as, tragically, we only have three accepted prefixes here.

2022-09-08 18:58 UTC, BBBBAface commented
> Window spawners spawn grilles under them, you should remove the grilles on the same tiles as your window spawners. In addition, you should put the ID back on the door, the linters just didn't like the ID var on the docking port. I'd also like you to replace the bridge holopad with a holopad/emergency/command, as most/all of our ships have one and that one in particular can help with access issues faced by a crew. And if I remember correctly, cyclelink helpers only work on doors in cardinal directions from each other. If you want the airlock to cycle in that way you'll need cyclelink_helper_target.

The airlock is fully functional as-is, this ship has been playtested quite a bit. I'm fixing the issues and updating the branch.

2022-09-08 19:22 UTC, BBBBAface commented
I put the id back on the door and it returns an error again, should I just delete it?

2022-09-08 21:42 UTC, GuiltyNeko commented
Ah, on doors, the proper var name is id_tag. That should do it.

2022-09-10 06:33 UTC, GuiltyNeko approved these changes
I'll TM this on the next round of testmerges

2022-10-17 00:48 UTC, BBBBAface commented
fixing my GitHub stuffi messed up awhile back, im just going to redo this pr

2022-10-17 00:59 UTC, closed without merging